steps:
# Install dependencies
- name: 'python:3.10-slim'
  entrypoint: 'pip'
  args: ['install', '-r', 'requirements.txt', '--user']

# Lint with pylint
- name: 'python:3.10-slim'
  entrypoint: 'pylint'
  args: ['--rcfile=.pylintrc', '*.py']

# Test with pytest
- name: 'python:3.10-slim'
  entrypoint: 'pytest'
  args: ['tests/']

# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', '$_AR_HOSTNAME/$_PROJECT_ID/$_REPO_NAME/$COMMIT_SHA', '.']

# Push the container image to Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', '$_AR_HOSTNAME/$_PROJECT_ID/$_REPO_NAME/$COMMIT_SHA']

# Deploy to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'gcloud'
  args: [
    'run', 'deploy', 'devops-mcp-server',
    '--image', '$_AR_HOSTNAME/$_PROJECT_ID/$_REPO_NAME/$COMMIT_SHA',
    '--region', '$_CLOUD_RUN_REGION',
    '--platform', 'managed',
    '--quiet'
  ]

images:
- '$_AR_HOSTNAME/$_PROJECT_ID/$_REPO_NAME/$COMMIT_SHA'
