name: ragdocs
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - aiohttp>=3.8.0
  - beautifulsoup4>=4.12.0
  - pymupdf>=1.23.0
  - python-dotenv>=1.0.0
  - pip:
    - mcp>=1.2.0
    - qdrant-client>=1.7.0
    - openai>=1.12.0
